import fs from 'node:fs'; import vm from 'node:vm'; import path from 'node:path';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');let e=[];
const req=['index.html','stock.html','styles.css','js/core.js','js/pricing.js','js/app.js','js/stock.js','js/supabase-config.js','data/catalogue.json','data/catalogue-item-de-base.json','data/pricing-model.json'];for(const f of req)if(!fs.existsSync(path.join(root,f)))e.push(`Absent: ${f}`);
for(const f of ['js/core.js','js/pricing.js','js/app.js','js/stock.js','js/supabase-config.js'])try{new vm.Script(fs.readFileSync(path.join(root,f),'utf8'),{filename:f});}catch(x){e.push(`${f}: ${x.message}`);}
let model;try{model=JSON.parse(fs.readFileSync(path.join(root,'data/pricing-model.json'),'utf8'));}catch(x){e.push(`pricing-model: ${x.message}`);}if(model?.affixes?.A112?.p!==2)e.push('A112 doit être P2.');
const ids=new Map();for(const file of ['data/catalogue.json','data/catalogue-item-de-base.json']){let a=[];try{a=JSON.parse(fs.readFileSync(path.join(root,file),'utf8'));}catch(x){e.push(`${file}: ${x.message}`);continue;}for(const it of a){if(!it?.id){e.push(`${file}: objet sans id`);continue;}if(ids.has(it.id))e.push(`ID dupliqué ${it.id}`);ids.set(it.id,file);const s=it.cofSpec;if(s&&model){const dedicated=String(it.category||'').toLowerCase().includes('consommable');const knownBase=!s.base||Boolean(model.bases[s.base]);if(s.base&&!knownBase&&!dedicated)e.push(`${it.id}: base inconnue ${s.base}`);if(knownBase)for(const af of (s.affixes||[]))if(!model.affixes[af])e.push(`${it.id}: affixe inconnu ${af}`);}}}
for(const page of ['index.html','stock.html']){const h=fs.readFileSync(path.join(root,page),'utf8');for(const m of h.matchAll(/(?:src|href)="([^"]+)"/g)){const u=m[1];if(/^(https?:|#)/.test(u))continue;if(!fs.existsSync(path.join(root,u)))e.push(`${page}: chemin absent ${u}`);}}
const mf=path.join(root,'assets/icons/manifest.json');if(fs.existsSync(mf)){try{const man=JSON.parse(fs.readFileSync(mf,'utf8'));for(const entry of (Array.isArray(man)?man:[])){for(const variant of (entry?.variants||[])){const rel=variant?.path;if(rel&&!fs.existsSync(path.join(root,'assets/icons',rel)))e.push(`Icône ${entry?.icon_key||entry?.name||'?'}: fichier absent ${rel}`);}}}catch(x){e.push(`manifest icônes: ${x.message}`);}}
if(e.length){console.error(e.join('\n'));process.exit(1)}console.log(`AlaricCode V2: validation OK (${ids.size} objets).`);
